name: Unit Test

on: [ push, pull_request ]

jobs:
  build:
    runs-on: Ubuntu

    steps:
    - uses: actions/checkout@v2

    - name: Fastlane Scan # Workspace와 Scheme는, 본인의 프로젝트에 맞게 설정해야 합니다.
      run: fastlane scan --workspace "MyProject.xcworkspace" --scheme "MyScheme"
